### ISSUE TITLE
Red on white code snippets are hard to read

### ISSUE THREAD

**Issue by hyperoceanic** [puretype/feedback#1]
Hi Matt, I'm trying to read your blog post about maps in Elixir, here: https://blog.puretype.ai/map-lookup-in-elixir

Your red text on bright white code snippets within a normal white text on black background are very difficult to read.

I don't know whats going on visually but it feels like the text equivalent of reading under a strobe light.

Could you please experiment with using eg white text on a dark-grey background for code snippets instead?

**Comment by mwhitworth** [comment]
Hi - thanks for bringing this to my attention. Apologies for the discomfort.

I've changed the code background colour to a darker grey, and the emphasis font to a much subtler orange. Is that now easier to read?

(I will raise this as an issue to the upstream theme developers too)

**Comment by hyperoceanic** [comment]
Hi Matthew - thanks for the quick response. It is a bit easier to read,
yes.

I find myself setting your --color-accent:  style value to  #000000 though.

Regards
Mark

**Comment by mwhitworth** [comment]
That's tweaked now too!
